source 'https://rubygems.org'

gem 'rails', '4.2.1'

gem 'haml-rails'
gem 'sqlite3'
gem 'therubyracer', platforms: :ruby

group :development, :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'minitest'
  gem 'pry-rails'
  gem 'rspec-rails', '>= 3.2'
  gem 'spork'
  gem 'spring'

  gem 'delta_test', path: '../..'
end
