source 'https://rubygems.org'

gem 'rails', '4.2.1'

gem 'sqlite3'
gem 'therubyracer', platforms: :ruby
gem 'haml-rails'

group :development, :test do
  gem 'pry-rails'
  gem 'spring'
  gem 'rspec-rails', '>= 3.2'

  gem 'delta_test', path: '../..'
end
